version: '3.8'

services:
  jupyter:
    image: jupyter/datascience-notebook:2023-02-28
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - /opt/lab1:/opt/lab1"
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local