version: '3.8'

services:
  jupyter:
    image: jupyter/datascience-notebook:2023-02-28
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - /opt/lab1:/opt/lab1"
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

networks:
  app_network:

volumes:
  mongo_data: